name: CaSILE
description: The CaSILE toolkit, a book publishing workflow employing SILE and
  other wizardry.
inputs:
  args:
    description: Arguments passed to CLI; defaults to ‘make’.
    required: false
    default: make
outputs:
  DISTDIR:
    description: Output directory
  PROJECT:
    description: Project name
  VERSION:
    description: Version string
runs:
  using: docker
  image: docker://ghcr.io/sile-typesetter/casile:v0.4.6
  args:
    - ${{ inputs.args }}
branding:
  icon: printer
  color: orange
