SILE.registerCommand("listarea", function (options, content)
  SILE.settings.temporarily(function ()
    SILE.settings.set("document.rskip", SILE.nodefactory.newGlue("10pt"))
    SILE.settings.set("document.lskip", SILE.nodefactory.newGlue("20pt"))
    SILE.settings.set("document.parindent", SILE.nodefactory.zeroGlue)
    SILE.process(content)
  end)
  SILE.call("noindent")
end)

SILE.registerCommand("listitem", function (options, content)
  SILE.call("glue", { width = "-1em" })
  SILE.typesetter:typeset("•")
  SILE.call("glue", { width = "0.3em" })
  SILE.process(content)
  SILE.call("smallskip")
end)
