SILE.registerCommand("listarea", function (options, content)
  SILE.settings.temporarily(function ()
    SILE.settings.set("document.rskip", SILE.nodefactory.newGlue(tostring(SILE.settings.get("document.parindent").width)))
    SILE.settings.set("document.lskip", SILE.nodefactory.newGlue(tostring(SILE.settings.get("document.parindent").width)))
    SILE.settings.set("document.parindent", SILE.nodefactory.zeroGlue)
    SILE.process(content)
  end)
  SILE.call("noindent")
end)

SILE.registerCommand("listitem", function (options, content)
  local lskip = SILE.settings.get("document.lskip").width
  SILE.call("kern", { width = tostring(lskip * -0.5) })
  SILE.call("rebox", { width = tostring(lskip * 0.5) }, { "•" })
  SILE.process(content)
  SILE.call("smallskip")
end)
