#!/usr/bin/env bash

echo docker build \
	--build-arg VCS_REF=$(git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g') \
	--build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
	-t $IMAGE_NAME \
	.
